import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

import Header from "@/components/websiteComponent/layout/Header";
import Footer from "@/components/websiteComponent/layout/Footer";
import ReduxProvider from "@/redux/storeprovider";
import { GetProfile } from "@/utils/ServerAPi";
import { Toaster } from "sonner";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default async function RootLayout({ children }) {
  let user = null
  const response = await GetProfile()
 if(response?.success){
  user = response.user
 }
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">

        <ReduxProvider>

          <Header user= {user} />

          <main className="flex-1">
            {children}
          </main>

          <Footer />
        <Toaster position="top-right" richColors />


        </ReduxProvider>

      </body>

    </html>
  );
}